/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddVenue: typeof import('./src/components/AddVenue.vue')['default']
    AiEditor: typeof import('./src/components/AiEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GenerateMaterialCode: typeof import('./src/components/GenerateMaterialCode.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    MapActivity: typeof import('./src/components/MapActivity.vue')['default']
    MapIcon: typeof import('./src/components/MapIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
